name: moinsen_speech
description: Flutter Dart Package to help with speech interaction with minimal effort.
version: 0.0.1
homepage: https://www.moinsen.dev/flutter/packages/moinsen_speech
repository: https://github.com/moinsen-dev/moinsen_speech

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  speech_to_text: ^6.3.0
  provider: ^6.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.1.1

flutter:
